--Star Schema DW--
--Drop The Tables If They Exist In The Database--
DROP TABLE FACT_SALES CASCADE CONSTRAINTS;
DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE DIM_STORE CASCADE CONSTRAINTS;
DROP TABLE DIM_SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE DIM_TIME CASCADE CONSTRAINTS;


--Create Store Dimension Table--
CREATE TABLE DIM_STORE 
             (STORE_ID VARCHAR2(4), 
              STORE_NAME VARCHAR2(20) NOT NULL);                  
ALTER TABLE  DIM_STORE ADD CONSTRAINT PK_STORE_ID PRIMARY KEY (STORE_ID);

--Create Product Dimension Table--
CREATE TABLE DIM_PRODUCT
            (PRODUCT_ID VARCHAR2(6), 
             PRODUCT_NAME VARCHAR2(30) NOT NULL, 
             PRODUCT_PRICE VARCHAR2(10) NOT NULL);                          
ALTER TABLE  DIM_PRODUCT ADD CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (PRODUCT_ID);
 
 --Create Customer Dimension Table--
CREATE TABLE DIM_CUSTOMER
            (CUSTOMER_ID VARCHAR2(4), 
             CUSTOMER_NAME VARCHAR2(30) NOT NULL);
ALTER TABLE  DIM_CUSTOMER ADD CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID);
            
--Create Time Dimension Table--
CREATE TABLE DIM_TIME 
            (T_DATE DATE NOT NULL,
             T_YEAR NUMBER(4) NOT NULL, 
             T_MONTH NUMBER(2) NOT NULL, 
             T_QUARTER NUMBER(1) NOT NULL);
                                  
ALTER TABLE  DIM_TIME ADD CONSTRAINT PK_T_DATE PRIMARY KEY (T_DATE);
ALTER TABLE  DIM_TIME ADD CONSTRAINT UK_T_DATE UNIQUE (T_DATE, T_YEAR,T_MONTH, T_QUARTER);

--Create Supplier Dimension Table--
CREATE TABLE DIM_SUPPLIER
            (SUPPLIER_ID VARCHAR2(5), 
             SUPPLIER_NAME VARCHAR2(30) NOT NULL);                
             ALTER TABLE  DIM_SUPPLIER ADD CONSTRAINT PK_SUPPLIER_ID PRIMARY KEY (SUPPLIER_ID);

--Create Fact Table--
CREATE TABLE FACT_SALES 
            (STORE_ID VARCHAR2(4) NOT NULL, 
             SUPPLIER_ID VARCHAR2(5) NOT NULL, 
             PRODUCT_ID VARCHAR2(6) NOT NULL, 
             CUSTOMER_ID VARCHAR2(4) NOT NULL, 
             TRANSACTION_ID NUMBER(8,0) NOT NULL, 
             T_DATE DATE NOT NULL, 
             QUANTITY NUMBER(3,0) NOT NULL, 
             TOTAL_SALES NUMBER(10,2) NOT NULL);                        
ALTER TABLE  FACT_SALES ADD CONSTRAINT FK_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES DIM_STORE(STORE_ID);
ALTER TABLE  FACT_SALES ADD CONSTRAINT FK_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID);
ALTER TABLE  FACT_SALES ADD CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID);
ALTER TABLE  FACT_SALES ADD CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID);
ALTER TABLE  FACT_SALES ADD CONSTRAINT FK_TRAN_DATE FOREIGN KEY (T_DATE) REFERENCES DIM_TIME(T_DATE);
ALTER TABLE  FACT_SALES ADD CONSTRAINT UN_SALES_DETAIL UNIQUE (TRANSACTION_ID, T_DATE);
